# Generated by Django 2.0.6 on 2018-07-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('subject', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=15)),
            ],
        ),
    ]
