# Generated by Django 2.0.6 on 2018-07-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_districtinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtinfo',
            name='division',
            field=models.CharField(default='dhaka', max_length=50),
            preserve_default=False,
        ),
    ]
