# Generated by Django 2.2.2 on 2019-06-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_districtinfo_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpazilaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('population', models.IntegerField()),
                ('division', models.CharField(max_length=50)),
            ],
        ),
    ]
